# Generated by Django 3.2.4 on 2022-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SBCShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShareLink', models.CharField(max_length=32)),
                ('ShareFileInfo', models.CharField(max_length=500)),
                ('useremail', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=20)),
                ('ShareTime', models.IntegerField()),
                ('toUser', models.CharField(max_length=32)),
            ],
        ),
    ]
