# Generated by Django 3.2.4 on 2022-01-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileMd5', models.CharField(max_length=256)),
                ('FilePath', models.CharField(max_length=256)),
                ('FileName', models.CharField(max_length=256)),
            ],
        ),
    ]
