# Generated by Django 3.2.10 on 2022-01-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vcodemode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=32)),
                ('Vcode', models.CharField(max_length=4)),
                ('ipv4', models.CharField(max_length=32)),
                ('ipv6', models.CharField(max_length=200)),
                ('islocked', models.IntegerField()),
                ('locklevel', models.IntegerField()),
                ('firstrequesttime', models.IntegerField()),
                ('lastrequesttime', models.IntegerField()),
                ('retimesper', models.IntegerField()),
            ],
        ),
    ]
