# Generated by Django 3.2.16 on 2023-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SBCManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileStock', models.CharField(max_length=256)),
                ('UserStock', models.CharField(max_length=256)),
                ('SBCStockSize', models.IntegerField()),
                ('SBCUser0', models.CharField(max_length=20)),
                ('SBCUserPass0', models.CharField(max_length=20)),
                ('SBCManageEmail', models.CharField(max_length=30)),
                ('par1', models.CharField(max_length=256)),
                ('par2', models.CharField(max_length=256)),
                ('par3', models.CharField(max_length=256)),
            ],
        ),
    ]
