# Generated by Django 3.2.12 on 2022-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=32)),
                ('FileMd5', models.CharField(max_length=100)),
                ('FileType', models.CharField(max_length=10)),
                ('FilePath', models.CharField(max_length=200)),
                ('Expansion', models.CharField(max_length=200)),
            ],
        ),
    ]
